### ISSUE TITLE
Release flow has fatal errors due to auth

### ISSUE THREAD

**Issue by jenweber** [ember-learn/tool-new-release#25]
The current auth flow results in this error:

> remote: Support for password authentication was removed on August 13, 2021. Please use a personal access token instead.
> remote: Please see https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information.
> fatal: Authentication failed for 'https://github.com/ember-learn/guides-source.git/'

### Non fatal error in a script outside this repo
In guides-source, if I run the release script separately, the script fails to create a PR. Issue: https://github.com/ember-learn/guides-source/issues/1736  I can work around by creating a PR manually.

**Comment by locks** [comment]
I believe this is due to the fact that you cloned using the HTTPS link `Authentication failed for 'https://github.com/ember-learn/guides-source.git/'`. I use the SSH one, `git@github.com:ember-learn/guides-source.git`, so didn't have this problem?

**Comment by locks** [comment]
I don't think this is relevant anymore.
